#cloud-config
repo_update : true
repo_upgrade : all

packages:
- httpd
- mariadb-server

runcmd:
- yum install httpd
- yum install mariadb-server
- sudo systemctl start httpd
- sudo systemctl enable httpd
- sudo systemctl start mariadb
- sudo systemctl enable mariadb
- [ sh, -c, "usermod -a -G apache root"]
- [ sh, -c, "chown -R root:apache /var/www"]
- chmod 2775 /var/www


